import Head from 'next/head'
import CheckAuth from './Auth/checkAuth'


export default function Home() {
  var isLoggedIn = false
  const checkAuth = () => {
    if(typeof window !== 'undefined') {
      if(window.localStorage.hasOwnProperty('token')) {
       return true
      } else {
      return false
      }
    }
  }
  return (
    <>
      <Head>
        <title>PitonShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <CheckAuth />
   
      
      
  
    </>
  )
}
