import Head from 'next/head'
import Register from './Auth/Register'
import Products from './Products/Products'
import CheckAuth from './Auth/CheckAuth'
import ProductDetail from './Products/ProductDetail'



export default function Home() {
  var isLoggedIn = false
  const checkAuth = () => {
    if(typeof window !== 'undefined') {
      if(window.localStorage.hasOwnProperty('token')) {
       return true
      } else {
      return false
      }
    }
  }
  return (
    <>
      <Head>
        <title>PitonShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<CheckAuth />
      {/* <Login/> */}
      {/* <Products/> */}
      {/* <ProductDetail/> */}
      
      
  
    </>
  )
}
